### PR TITLE
Added itemsShow parametr to show fixed numbers of items

### PR DESCRIPTION
**Pull request by kirillkostko**
Hello!
I've added a new property that makes visible a specified number of elements. If you find it useful, please accept this pull request.

Best regards,
Kirill.

### CODE REVIEW

**Comment by basti1253** [comment]
Hi Kirill,

thank you very much for your pull request. Mhm - I wanted to keep the options as slim as possible - three new option properties doing roughly the same looks like too much ;). Instead of adding itemsShow, startItem (redundant as you may pass active index) and endItem how about a simple visibile property? I'm not sure about this too as the outer coverflow container handles this by css (overflow:hidden) anyway so I removed that property in earlier versions. What do you think? Is it ok to handle visible item count by container width?

best regards

**Comment by kirillkostko** [comment]
Hi Sebastian,
Thank you for your comment. Sorry I made a mistake. For that pull request I wanted only itemsShow option. This option is useful when the container does not hide all the necessary items. For example, I use a box-shadow hover, so I have to reserve widths for the elements at the edges.

startItem and endItem i use to prevent scroll. Because on one page I need a standard carousel and coverflow, and I don't want an additional library. These options should be excluded.

**Comment by basti1253** [comment]
Hey Kirill,

I cherry-picked your commit and renamed the configuration property to 'visibleAside'. Instead of passing a maximum of visible items you just configure how many neighbour items are visible to the left/right. 
https://github.com/coverflowjs/coverflow/commit/95cedf763c342a80028f0c7a44cb039ee997410e

Hope that fits your original purpose. I'll package a release after adding a unit test and extending the docs.

best regards

**Comment by kirillkostko** [comment]
Hi Sebastian,
Sorry for the delay. Thank you! It works!

**Pull request closed without merging**
